apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: prometheus-template
message: |-
  The following service(s) have been created in your project: ${PROMETHEUS_SERVICE_NAME}.
  For more information about using this template, including OpenShift considerations, contact the rocketchat community.
metadata:
  annotations:
    description: |-
      prometheus Template
    iconClass: icon-other-unknown
    openshift.io/display-name: prometheus-openshift201
    openshift.io/documentation-url: https://github.com/bcdevops/devops-platform-workshops
    openshift.io/long-description: This template provides a sample Loki for lab purposes.
    openshift.io/provider-display-name: BCDevOps
    openshift.io/support-url: https://github.com/bcdevops/
    tags: prometheus
  name: prometheus-template
objects:
- apiVersion: v1
  kind: Service
  metadata:    
    labels:
      app: ${PROMETHEUS_SERVICE_NAME}
      chart: prometheus-8.11.4
      component: ${PROMETHEUS_SERVICE_NAME}
      heritage: Tiller
      release: ${PROMETHEUS_SERVICE_NAME}
    name: ${PROMETHEUS_SERVICE_NAME}
  spec:
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9090
    selector:
      app: ${PROMETHEUS_SERVICE_NAME}
      component: ${PROMETHEUS_SERVICE_NAME}
      release: ${PROMETHEUS_SERVICE_NAME}
    sessionAffinity: None
    type: ClusterIP
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "3"
    generation: 5
    labels:
      app: ${PROMETHEUS_SERVICE_NAME}
      chart: prometheus-8.11.4
      component: ${PROMETHEUS_SERVICE_NAME}
      heritage: Tiller
      release: ${PROMETHEUS_SERVICE_NAME}
    name: ${PROMETHEUS_SERVICE_NAME}
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: ${PROMETHEUS_SERVICE_NAME}
        component: ${PROMETHEUS_SERVICE_NAME}
        release: ${PROMETHEUS_SERVICE_NAME}
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: ${PROMETHEUS_SERVICE_NAME}
          chart: prometheus-8.11.4
          component: ${PROMETHEUS_SERVICE_NAME}
          heritage: Tiller
          release: ${PROMETHEUS_SERVICE_NAME}
      spec:
        containers:
        - args:
          - --volume-dir=/etc/config
          - --webhook-url=http://127.0.0.1:9090/-/reload
          image: jimmidyson/configmap-reload:v0.2.2
          imagePullPolicy: Always
          name: ${PROMETHEUS_SERVICE_NAME}-configmap-reload
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/config
            name: config-volume
            readOnly: true
        - args:
          - --config.file=/etc/config/prometheus.yml
          - --storage.tsdb.path=/data
          - --web.console.libraries=/etc/prometheus/console_libraries
          - --web.console.templates=/etc/prometheus/consoles
          - --web.enable-lifecycle
          image: prom/prometheus:v2.9.2
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /-/healthy
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 30
          name: ${PROMETHEUS_SERVICE_NAME}
          ports:
          - containerPort: 9090
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /-/ready
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 30
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/config
            name: config-volume
          - mountPath: /data
            name: storage-volume
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: default
        serviceAccountName: default
        terminationGracePeriodSeconds: 300
        volumes:
        - configMap:
            defaultMode: 420
            name: ${PROMETHEUS_SERVICE_NAME}
          name: config-volume
        - name: storage-volume
          persistentVolumeClaim:
            claimName: ${PROMETHEUS_SERVICE_NAME}
- apiVersion: v1
  kind: ConfigMap
  metadata:
    labels:
      app: ${PROMETHEUS_SERVICE_NAME}
      chart: prometheus-8.11.4
      component: ${PROMETHEUS_SERVICE_NAME}
      heritage: Tiller
      release: ${PROMETHEUS_SERVICE_NAME}
    name: ${PROMETHEUS_SERVICE_NAME}
  data:
    alerts: |
      {}
    prometheus.yml: |
      global:
        evaluation_interval: 1m
        scrape_interval: 1m
        scrape_timeout: 10s
      rule_files:
      - /etc/config/rules
      - /etc/config/alerts
      scrape_configs:
      - job_name: prometheus
        static_configs:
        - targets:
          - localhost:9090
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
        - role: pod
          namespaces:
            names:
              - ${PROMETHEUS_SERVICE_NAME}
        relabel_configs:
        - action: keep
          regex: true
          source_labels:
          - __meta_kubernetes_pod_annotation_prometheus_io_scrape
        - action: replace
          regex: (.+)
          source_labels:
          - __meta_kubernetes_pod_annotation_prometheus_io_path
          target_label: __metrics_path__
        - action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          source_labels:
          - __address__
          - __meta_kubernetes_pod_annotation_prometheus_io_port
          target_label: __address__
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - action: replace
          source_labels:
          - __meta_kubernetes_namespace
          target_label: kubernetes_namespace
        - action: replace
          source_labels:
          - __meta_kubernetes_pod_name
          target_label: kubernetes_pod_name
    rules: |
      {}
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
    labels:
      app: ${PROMETHEUS_SERVICE_NAME}
    name: ${PROMETHEUS_SERVICE_NAME}
  spec:
    host: ${PROMETHEUS_SERVICE_NAME}.${ROUTE_SUBDOMAIN}
    port:
      targetPort: http
    to:
      kind: Service
      name: ${PROMETHEUS_SERVICE_NAME}
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      component: ${PROMETHEUS_SERVICE_NAME}
      app: ${PROMETHEUS_SERVICE_NAME}
      release: ${PROMETHEUS_SERVICE_NAME}
      chart: prometheus-8.11.4
      heritage: Tiller
    name: ${PROMETHEUS_SERVICE_NAME}
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: "1Gi"
parameters:
- description: The name of the Prometheus service to connect to.
  displayName: Prometheus Service Name
  name: PROMETHEUS_SERVICE_NAME
  required: true
  value: prometheus
- description: Default route subdomain
  displayName: Route subdomain
  name: ROUTE_SUBDOMAIN
  required: true
  value: pathfinder.gov.bc.ca
