#!/usr/bin/env groovy

//ENV Vars
def TOOLS_NAMESPACE = "s4g19x-dkelsey-openshift201-may2019-tools"
def DEV_NAMESPACE = "s4g19x-dkelsey-openshift201-may20190-dev"
def PROD_NAMESPACE = "s4g19x-dkelsey-openshift201-may2019-prod"


//Pipeline
node {
            stage ('Build Stage'){
                dir ('simple_pipeline') {
                    checkout scm
                    sh "oc get projects"
                    sh "oc whomai"
                }
            }
    }
